logo: # add logo name
title: Women Techmakers Switzerland
description: > WTM provides visibility, community, and resources for women in technology to drive innovation and participation in the field. The events are designed to promote an environment of inclusion for women in technology, as well as celebrate women leading the industry. WTM is part of GDG Zurich and we're committed to making people off all genders welcome in our community.
Disclaimer: GDG Women Techmakers Switzerland is an independent group; our activities and the opinions expressed here should in no way be linked to Google, the corporation. To learn more about the GDG program, visit https://developers.google.com/groups/
permalink: ':title/'
#baseurl: "/bef" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email: your-email@domain.com # your email
phone: (496)-169-6557 # your pnone number
website: https://dwayne.example.com # you website

# Social link
google_url:    https://www.womentechmakers.com/directory
twitter_url:   https://twitter.com/WomenTechmakers
meetup_url:    https://www.meetup.com/wtm-switzerland

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
